services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing
    restart: unless-stopped
    volumes:
      - ./status.json:/usr/share/nginx/html/status.json:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
