services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: landing
    restart: unless-stopped
    depends_on:
      - landing-api
    volumes:
      - ./status.json:/usr/share/nginx/html/status.json
    networks:
      - proxy-network

  landing-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: landing-api
    restart: unless-stopped
    volumes:
      - landing-data:/data
    networks:
      - proxy-network

volumes:
  landing-data:

networks:
  proxy-network:
    external: true
